# Generated by Django 4.2.27 on 2026-01-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adhar_app', '0002_destination_parent_alter_destination_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('student', 'Student Tour'), ('wedding', 'Wedding'), ('medical', 'Medical Tourism')], default='general', max_length=20),
        ),
    ]
