# Generated by Django 5.2.10 on 2026-01-16 06:02

import Adhar_django.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adhar_app', '0003_destination_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(storage=Adhar_django.storage.SupabaseStorage, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(storage=Adhar_django.storage.SupabaseStorage, upload_to='packages/'),
        ),
    ]
